"""empty message

Revision ID: 0c34ef09c683
Revises: c8b8c05b1eba
Create Date: 2025-08-02 01:21:48.359161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c34ef09c683'
down_revision = 'c8b8c05b1eba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atuacao', schema=None) as batch_op:
        batch_op.alter_column('personagem',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atuacao', schema=None) as batch_op:
        batch_op.alter_column('personagem',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
