"""empty message

Revision ID: 3925fd11c61c
Revises: 5c7feee0f885
Create Date: 2025-08-01 16:16:45.961594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3925fd11c61c'
down_revision = '5c7feee0f885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temporada', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ano', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filme', schema=None) as batch_op:
        batch_op.drop_column('ano')
        batch_op.drop_column('temporada')

    # ### end Alembic commands ###
