"""Adiciona modelo Filme com relação nomeada

Revision ID: 57a294351af3
Revises: 
Create Date: 2025-07-31 15:26:28.220675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57a294351af3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_episodio')
    with op.batch_alter_table('episodio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filme_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_episodio_filme_id', 'filme', ['filme_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episodio', schema=None) as batch_op:
        batch_op.drop_constraint('fk_episodio_filme_id', type_='foreignkey')
        batch_op.drop_column('filme_id')

    op.create_table('_alembic_tmp_episodio',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=100), nullable=False),
    sa.Column('numero', sa.VARCHAR(length=10), nullable=False),
    sa.Column('avaliacao', sa.FLOAT(), nullable=True),
    sa.Column('filme_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['filme_id'], ['filme.id'], name=op.f('fk_episodio_filme_id')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
