"""Adicionando uma coluna na tabela ator_filme

Revision ID: 5c27e6c92a88
Revises: ccbad2f076aa
Create Date: 2025-08-01 20:58:39.914723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c27e6c92a88'
down_revision = 'ccbad2f076aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ator_filme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personagem', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ator_filme', schema=None) as batch_op:
        batch_op.drop_column('personagem')

    # ### end Alembic commands ###
