"""Torna filme_id obrigatório

Revision ID: 5c7feee0f885
Revises: 57a294351af3
Create Date: 2025-07-31 15:28:21.248530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c7feee0f885'
down_revision = '57a294351af3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episodio', schema=None) as batch_op:
        batch_op.alter_column('filme_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episodio', schema=None) as batch_op:
        batch_op.alter_column('filme_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
