"""empty message

Revision ID: 61db80595ecd
Revises: c4ea2e433fb4
Create Date: 2025-08-06 18:33:42.056574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61db80595ecd'
down_revision = 'c4ea2e433fb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('senha')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha', sa.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
