"""empty message

Revision ID: b20e96b8ab11
Revises: c816624d7aea
Create Date: 2025-08-06 15:13:46.828354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b20e96b8ab11'
down_revision = 'c816624d7aea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('usuario',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('descricao',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('descricao',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('usuario',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
