"""empty message

Revision ID: be849d98d846
Revises: 0c34ef09c683
Create Date: 2025-08-04 00:37:30.978402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be849d98d846'
down_revision = '0c34ef09c683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_filme')
    with op.batch_alter_table('filme', schema=None) as batch_op:
        batch_op.alter_column('descricao',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('temporada',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('ano',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filme', schema=None) as batch_op:
        batch_op.alter_column('ano',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('temporada',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('descricao',
               existing_type=sa.TEXT(),
               nullable=True)

    op.create_table('_alembic_tmp_filme',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=100), nullable=False),
    sa.Column('descricao', sa.TEXT(), nullable=False),
    sa.Column('temporada', sa.INTEGER(), nullable=False),
    sa.Column('ano', sa.INTEGER(), nullable=False),
    sa.Column('trailer', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
