"""empty message

Revision ID: c4ea2e433fb4
Revises: b20e96b8ab11
Create Date: 2025-08-06 16:41:57.860846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4ea2e433fb4'
down_revision = 'b20e96b8ab11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_avaliacao_usuario_id', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('senha_hash', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint('uq_usuario_fk_avaliacao_usuario_id', ['fk_avaliacao_usuario_id'])
        batch_op.drop_column('usuario')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('senha', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint('uq_usuario_fk_avaliacao_usuario_id', type_='unique')
        batch_op.drop_column('senha_hash')
        batch_op.drop_column('fk_avaliacao_usuario_id')

    # ### end Alembic commands ###
