"""Criado usuario

Revision ID: c816624d7aea
Revises: 4d64f3571d7d
Create Date: 2025-08-06 15:07:41.251866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c816624d7aea'
down_revision = '4d64f3571d7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episodio', schema=None) as batch_op:
        batch_op.drop_column('avaliacao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episodio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avaliacao', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
