"""empty message

Revision ID: c8b8c05b1eba
Revises: e98f0e84f51b
Create Date: 2025-08-01 22:02:01.135065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8b8c05b1eba'
down_revision = 'e98f0e84f51b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ator_filme')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ator_filme',
    sa.Column('ator_id', sa.INTEGER(), nullable=False),
    sa.Column('filme_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['ator_id'], ['ator.id'], ),
    sa.ForeignKeyConstraint(['filme_id'], ['filme.id'], ),
    sa.PrimaryKeyConstraint('ator_id', 'filme_id')
    )
    # ### end Alembic commands ###
