"""empty message

Revision ID: ccbad2f076aa
Revises: e303b8934d73
Create Date: 2025-08-01 20:16:03.218518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccbad2f076aa'
down_revision = 'e303b8934d73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ator', schema=None) as batch_op:
        batch_op.alter_column('data_nascimento',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ator', schema=None) as batch_op:
        batch_op.alter_column('data_nascimento',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
