"""empty message

Revision ID: e0869f3ad0d2
Revises: 5c27e6c92a88
Create Date: 2025-08-01 21:15:01.157435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0869f3ad0d2'
down_revision = '5c27e6c92a88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ator_filme', schema=None) as batch_op:
        batch_op.alter_column('personagem',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ator_filme', schema=None) as batch_op:
        batch_op.alter_column('personagem',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
