"""empty message

Revision ID: e303b8934d73
Revises: 3925fd11c61c
Create Date: 2025-08-01 17:15:17.002875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e303b8934d73'
down_revision = '3925fd11c61c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_nascimento', sa.Date(), nullable=False))
        batch_op.drop_column('nascimento')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nascimento', sa.DATE(), nullable=False))
        batch_op.drop_column('data_nascimento')

    # ### end Alembic commands ###
