"""empty message

Revision ID: e98f0e84f51b
Revises: e0869f3ad0d2
Create Date: 2025-08-01 21:18:49.108163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e98f0e84f51b'
down_revision = 'e0869f3ad0d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ator_filme', schema=None) as batch_op:
        batch_op.drop_column('personagem')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ator_filme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personagem', sa.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
